Bag of words

In [238]:
import pandas as pd
import nltk
from nltk.tokenize import word_tokenize

In [239]:
sent1='It is good practice for us'
sent2='It was also good to know about it'
tokens=word_tokenize(sent1.lower())+word_tokenize(sent2.lower())
tokens=set(tokens)

In [240]:
df = pd.DataFrame([],index=[1,2],columns=list(tokens))
df

  practice good  was  for   us   is   to also know about   it
1      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN  NaN
2      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN  NaN

In [241]:
counts1=[word_tokenize(sent1.lower()).count(word) for word in df.columns]
counts2=[word_tokenize(sent2.lower()).count(word) for word in df.columns]

In [242]:
counts1

[1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1]

In [243]:
counts2

[0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 2]

In [244]:
df.iloc[0,:]=counts1
df.iloc[1,:]=counts2

In [245]:
df

  practice good was for us is to also know about it
1        1    1   0   1  1  1  0    0    0     0  1
2        0    1   1   0  0  0  1    1    1     1  2

In [246]:
from sklearn.feature_extraction.text import CountVectorizer

In [247]:
cvt=CountVectorizer()

In [248]:
new=cvt.fit_transform([sent1,sent2])

In [249]:
arr=new.toarray()

In [250]:
new

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 13 stored elements and shape (2, 11)>

In [251]:
cvt.get_feature_names_out()

array(['about', 'also', 'for', 'good', 'is', 'it', 'know', 'practice',
       'to', 'us', 'was'], dtype=object)

In [252]:
df1=pd.DataFrame([],index=[1,2],columns=cvt.get_feature_names_out())

In [253]:
df1.iloc[0,:]=arr[0]
df1.iloc[1,:]=arr[1]

In [254]:
df1

  about also for good is it know practice to us was
1     0    0   1    1  1  1    0        1  0  1   0
2     1    1   0    1  0  2    1        0  1  0   1

In [255]:
cvt=CountVectorizer(stop_words='english')

In [256]:
new=cvt.fit_transform([sent1,sent2])
df2=pd.DataFrame(new.toarray(),columns=cvt.get_feature_names_out())
df2

   good  know  practice
0     1     0         1
1     1     1         0

#### N-grams
#### why
- to find frequency of words in two sentences
- Bigram
    - combination of two words
- n grams
    - combination of n words

In [257]:
from sklearn.feature_extraction.text import CountVectorizer
cvt = CountVectorizer()
cvt=CountVectorizer(ngram_range=(1,2))
new = cvt.fit_transform([sent1,sent2])

In [258]:
cvt.get_feature_names_out()

array(['about', 'about it', 'also', 'also good', 'for', 'for us', 'good',
       'good practice', 'good to', 'is', 'is good', 'it', 'it is',
       'it was', 'know', 'know about', 'practice', 'practice for', 'to',
       'to know', 'us', 'was', 'was also'], dtype=object)

In [259]:
df=pd.DataFrame(new.toarray(),columns=cvt.get_feature_names_out())
df

,about,about it,also,also good,for,for us,good,good practice,good to,is,...,it was,know,know about,practice,practice for,to,to know,us,was,was also
0,0,0,0,0,1,1,1,1,0,1,...,0,0,0,1,1,0,0,1,0,0
1,1,1,1,1,0,0,1,0,1,0,...,1,1,1,0,0,1,1,0,1,1

#### TF-IDE Vectorizer : 
- #### Term Frequency 
    - Its no of times it appears in a document 
    - TF=No of times t appears in a document / total no terms in the document
- #### IDF 
    -  Inverse Document Frequency of a word is the measure of how significent tem is in whole corpus
    - IDF(t) = log_e(Total number of docs / no of docs with term t in it)

In [260]:
# Example
sent1='It was a beautiful rainy dat that made my day awesome'
sent2='We made it awesome by ading more flavors in it'

In [261]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [262]:
tfidf=TfidfVectorizer()

In [263]:
new=tfidf.fit_transform([sent1,sent2])

In [264]:
import pandas as pd

In [265]:
df=pd.DataFrame(new.toarray(),columns=tfidf.get_feature_names_out())
df

,ading,awesome,beautiful,by,dat,day,flavors,in,it,made,more,my,rainy,that,was,we
0,0.000000,0.243777,0.34262,0.000000,0.34262,0.34262,0.000000,0.000000,0.243777,0.243777,0.000000,0.34262,0.34262,0.34262,0.34262,0.000000
1,0.332642,0.236677,0.00000,0.332642,0.00000,0.00000,0.332642,0.332642,0.473355,0.236677,0.332642,0.00000,0.00000,0.00000,0.00000,0.332642

In [266]:
# read mreview file remove stopwords create tfidf vector reult

In [267]:
import os
sent=open('mreviews.txt','r').read()

In [268]:
sent

'This film is an absolute masterpiece that will stay with you long after the credits roll.\nA visually stunning and emotionally resonant cinematic experience that demands to be seen on the big screen.\nAn exhilarating ride from start to finish, easily standing out as one of the best films of the year.\nIt manages to exceed all expectations, delivering a thoroughly satisfying and triumphant cinematic event.\nThe lead delivers a career-defining performance that is both powerfully gripping and deeply moving.\nThe entire cast shares incredible chemistry, bringing a refreshing and grounded authenticity to the screen.\nEvery character is meticulously crafted, allowing the audience to forge a genuine emotional connection with their journeys.\nThe supporting cast shines brightly, each adding essential layers of depth and charm to the overarching narrative.\nThe director brilliantly weaves a complex narrative that is just as thought-provoking as it is immensely entertaining.\nWith its incredibly tight pacing and clever plot twists, the story never once loses its momentum.\nThe script is sharply written, balancing profound dramatic moments with perfectly timed, natural humor.\nIt takes a familiar genre and turns it on its head, offering a completely fresh and innovative perspective.\n'

In [275]:
tidif=TfidfVectorizer(stop_words='english')
new=tidif.fit_transform([sent])
df=pd.DataFrame(new.toarray(),columns=tidif.get_feature_names_out())
df

,absolute,adding,allowing,audience,authenticity,balancing,best,big,brightly,brilliantly,...,thought,tight,timed,triumphant,turns,twists,visually,weaves,written,year
0,0.090167,0.090167,0.090167,0.090167,0.090167,0.090167,0.090167,0.090167,0.090167,0.090167,...,0.090167,0.090167,0.090167,0.090167,0.090167,0.090167,0.090167,0.090167,0.090167,0.090167